### PR TITLE
Multiple improvements

### PR DESCRIPTION
**Pull request by rawiriblundell**
Hi there,
This is a suggested set of fixes and improvements.  I've tried to keep them split up into separate commits, so that you can review and cherry pick.

Cheers!

### CODE REVIEW

**Comment by GEROGIANNIS** [comment]
*Consistent cuddling*  ( ͡ ° ͜  °)

**Comment by GEROGIANNIS** [comment]
@rawiriblundell I love the improvements , the changes , everything . Waiting for my collaborator to also approve and we will surely merge it to main as soon as possible (っ´ω`c)♡ tnx for the help

**Review by lefterisgar — CHANGES_REQUESTED** [review]
The clipboard handling function needs a few changes. It should let the user know which package is missing if XDG_SESSION_TYPE is set.

**Comment by lefterisgar** [comment]
However, I agree with @GEROGIANNIS. The code is perfect otherwise and I'm really glad that someone has stepped in and decided to contribute to Limoji!

**Review by lefterisgar — APPROVED** [review]
Everything should be good now!

**Pull request merged**
